# codemcp configuration file
project_prompt = """
You MUST always obey the following rules:

Read the README.md and TODO.md documents to see what's going on

When told to "continue", or "continue where you left off",... use the
'branch_log' command to inspect the last commit you made and continue. I may
have left a commit after yours to help you out, inspect it and take it into
account.

You can use the 'hoogle' command to search for documentation about symbols in
any external dependency we have available. You should implement functionality
using existing dependencies when possible.

When editing cabal files, do not add version bounds to packages.

You MUST always run the 'cabal_test' command on every package you modify and fix any
errors. Do this after every edit that affects haskell code and fix errors before
proceeding.

When implementing new functions, first get the type signatures right leaving the
body as `error "function foo has not been implemented yet"`. Check with the
`test` command that everything compiles after every edit.

You MUST always run the 'hlint' command on every Haskell file after every testing
your edits and fix ALL the warnings and errors it reports.

You MUST always use Generic deriving mechanisms for JSON/YAML
serialization, never hand-code it.  Use DeriveAnyClass and
DuplicateRecordFields for nice field names. Use OverloadedRecordDot extension to disambiguate types on record access

You MUST always use explicit import and export lists.

## Final tasks

When your work is ready, you MUST:

1) Run the integration-tests.  ALL tests MUST pass! We allow no flaky tests here. Fix
them if they don't and repeat. If you get stuck write a FIXME
"""

[commands.format]
command = ["./run_format.sh"]
doc = "Accepts the name of the files that need formatting as arguments"

[commands.branch_log]
command = ["./run_branch_log.sh"]
doc = """
Show the log messages of the changes done in this branch with git log

Accepts an optional path list to restrict query to a specific set of files or
directories and rguments to limit the numer of commits or commit ranges
"""

[commands.branch_changed_files]
command = ["git", "diff", "--name-only", "origin/main...HEAD", "--"]
doc = """
List the file names that have been changed in this branch

Accepts an optional path list to restrict query to a specific set of files or
directories
"""

[commands.git_show]
command = ["git", "show"]
doc = """
Use "git show" to show the changes of a commit ot range of commits
"""

# Logging stuff
[logger]
# Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
verbosity = "DEBUG"

[commands.test]
command = ["nix", "flake", "check"]

[commands.cabal_build]
command = ["env", "-C", "./agent-vm", "cabal", "build"]
doc = "Runs cabal build. Accepts the name of a single package as an argument to run their specific tests"

[commands.cabal_test]
command = ["env", "-C", "./agent-vm", "cabal", "test"]
doc = "Runs cabal test. Accepts the name of a single package as an argument to run their specific tests"

[commands.lynx]
command = ["lynx", "-dump"]
doc = """
Use Lynx to view documentation links that hoogle shows
"""


[commands.hoogle]
command = ["hoogle"]
doc = """
Use Hoogle to search for symbols in available dependencies.

Before explaining the syntax of searches, we first give a list of example
searches with their meaning:

"map" Search for the text "map"
"con map" Search for the text "map" and the text "con"
"a -> a" Search for the type "a -> a"
":: a -> a" Search for the type "a -> a"
"a" Search for the text "a"
":: a" Search for the type "a"
"id :: a -> a" Search for the text "id" and the type "a -> a"
Searches can be either textual (a list of words), or by type (a type signature)
or both. A type search may optionally start with a "::" symbol. A search is
considered a text search unless it contains a combination of text and symbols,
or if it starts with (::). To search for both a type and a name, place a ::
between them, for example "undefined :: a"

Modules: Searches can be restricted to a particular module with +Module.Name, or
to avoid a module with -Module.Name. The command Module.Name.Foo is treated as
+Module.Name Foo.

Packages: Searches can be restricted to a particular package with +packagename,
or to avoid a package with -package. By default Hoogle will search a standard
set of packages.
"""

[commands.lint]
command = ["env", "-C", "./agent-vm", "hlint"]
doc = """
Run hlint on the file or directory passed as argument to report errors

When asked to lint every haskell file just call it like "lint ."
"""

[commands.integration-test]
command = ["timeout", "90s", "nix", "run", ".#integration-test", "--"]
doc = """
Runs the .#integration-test flake app with the arguments you pass"

Arguments are passed to the python script. Make sure you quote them properly!
"""
